[tools]
go = "1.26"
golangci-lint = "2.11.4"
"go:golang.org/x/pkgsite/cmd/pkgsite"= "latest"

[tasks."test"]
description = "Run tests"
run = "go test-v - race ./..."

[tasks."lint"]
description = "Run linters"
run = "golangci-lint run ./..."

[tasks."doc"]
description = "Generate documentation"
run = "pkgsite"

[tasks."tidy"]
description = "Run go tidy"
run = "go mod tidy"